name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for linux64
      run: yarn gulp release --linux64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-linux-snapshot-${{ env.revision }}
        path: release/rotorflight-configurator*


  macos:

    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for MacOS
      run: yarn gulp release --osx64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-macos-snapshot-${{ env.revision }}
        path: release/rotorflight-configurator*


  windows:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: |
        $release = $env:GITHUB_REF -replace '.*/',''
        echo "revision=$release" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Initialise build environment
      run: yarn install

    - name: Build release for windows
      run: yarn gulp release --win64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-windows-snapshot-${{ env.revision }}
        path: release/rotorflight-configurator*


  snapshot:

    runs-on: ubuntu-latest

    needs: [linux, windows, macos]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Download Linux Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-linux-snapshot-${{ env.revision }}

    - name: Download MacOS Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-macos-snapshot-${{ env.revision }}

    - name: Download Windows Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-windows-snapshot-${{ env.revision }}

    - name: Create Snapshot
      run: |
        gh release create ${GITHUB_REF##refs/tags/} --prerelease --notes-file "Snapshot.md" --title "Rotorflight Configurator Snapshot ${GITHUB_REF##*/}" rotorflight-configurator*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

